---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels: 
    app: my-app
spec: 
  templates:
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: my-container
          image: httpd
          ports:
            - containerport: 80
   repllicas: 3
   selector:
     metalabels:
       app: my-app
   strategy: 
     type: Rollingupdate
...

---
apiVersion: v1
kind: Service
metadata: 
  name: my-svc
spec: 
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
  selector: 
    app: my-app
...
