-----
apiVersion: v1
kind: Pod
metadata: 
   name: cbz-app
   label:
     app: cbz-app
spec:
   containers:
      - name: cbz-container
        image: 
        ports:
          - containerport: 80
      - name: tomcat-container
        image: tomcat
        port: 
          - containerport: 8080

.....