apiVersion: app/v1
kind: Deployment
metadata: 
  name: frontend
  labels: 
    app: frontend
spec: 
  template: 
     metadata: 
       labels: 
         app: frontend
    spec: 
      containers:
        - name: frontend
          image: PavanS2002/CEDE-19
          ports:
            - containerPort: 80
    replicas: 3
    selector:
      matchlables:
          app: frontend
    strategy: 
      type:  RollinUpdate
      